variable "prefix" {}
variable "postfix" {}
variable "s3_domain_name" {}
variable "domain_zone_id" {}
variable "domain_name" {}
variable "vpc_id" {}
variable "gitlab" {}
variable "web_alb" {}
variable "admin_aws_id" {}
