apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: '{{ .Values.Svc1Name }}'
  namespace: '{{ .Values.ArgoNameSpace }}'
spec:
  project: default
  source:
    repoURL: '{{ .Values.GitlabUrl }}/hans-s2s/hans-s2s-{{ .Values.Svc1Name }}.git'
    targetRevision: main
    path: 'helm/{{ .Values.Svc1Name }}'
    helm:
      valueFiles:
        - Values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
