apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: '{{ .Values.Svc2Name }}'
  namespace: '{{ .Values.ArgoNameSpace }}'
  annotations:
    argocd-image-updater.argoproj.io/image-list: 'svc2={{ .Values.ecr.repository.url }}'
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/allow-tags: regexp:^svc2-[0-9a-z]+$
    argocd-image-updater.argoproj.io/update-strategy: newest-build
spec:
  project: default
  source:
    repoURL: '{{ .Values.GitlabUrl }}/hans-s2s/hans-s2s-{{ .Values.Svc2Name }}.git'
    targetRevision: main
    path: 'helm/{{ .Values.Svc2Name }}'
    helm:
      valueFiles:
        - Values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
